"use server";

import { revalidatePath } from "next/cache";
import { Types } from "mongoose";
import { requireUserId } from "@/lib/dal";
import { connectToDatabase } from "@/lib/db";
import { StudyMaterial } from "@/models/StudyMaterial";
import { MaterialChunk } from "@/models/MaterialChunk";
import { createUploadUrl, deleteObject, headObject } from "@/lib/storage/s3";
import {
  FORMAT_MIME_TYPES,
  MAX_UPLOAD_BYTES,
  buildMaterialStorageKey,
  formatFromFilename,
  parseMaterialStorageKey,
} from "@/lib/study-materials/constants";
import { ConfirmUploadInputSchema, RequestUploadInputSchema } from "@/lib/study-materials/validation";
import { processStudyMaterial } from "@/lib/study-materials/processing";
import { courseBelongsToUser } from "./course-ownership";

export type UploadUrlResult =
  | { error: string }
  | { uploadUrl: string; storageKey: string; contentType: string };

export type ConfirmUploadResult = { error: string } | { materialId: string };

export async function requestMaterialUploadUrl(input: {
  filename: string;
  sizeBytes: number;
  courseId: string;
}): Promise<UploadUrlResult> {
  const userId = await requireUserId();

  const parsed = RequestUploadInputSchema.safeParse(input);
  if (!parsed.success) {
    return { error: parsed.error.issues[0]?.message ?? "Invalid input" };
  }

  const format = formatFromFilename(parsed.data.filename);
  if (!format) {
    return { error: "Only PDF, DOCX, and PPTX files are supported" };
  }

  await connectToDatabase();

  if (!(await courseBelongsToUser(parsed.data.courseId, userId))) {
    return { error: "Course not found" };
  }

  const storageKey = buildMaterialStorageKey(userId, format);
  const contentType = FORMAT_MIME_TYPES[format];
  const uploadUrl = await createUploadUrl(storageKey, contentType);

  return { uploadUrl, storageKey, contentType };
}

export async function confirmMaterialUpload(input: {
  storageKey: string;
  originalFilename: string;
  courseId: string;
}): Promise<ConfirmUploadResult> {
  const userId = await requireUserId();

  const parsed = ConfirmUploadInputSchema.safeParse(input);
  if (!parsed.success) {
    return { error: parsed.error.issues[0]?.message ?? "Invalid input" };
  }

  // The storage key was generated by requestMaterialUploadUrl above and
  // only ever echoed back by the client — this check is what stops a
  // client from "confirming" a key that isn't actually theirs.
  const keyInfo = parseMaterialStorageKey(parsed.data.storageKey);
  if (!keyInfo || keyInfo.userId !== userId) {
    return { error: "Invalid or unrecognized upload" };
  }

  await connectToDatabase();

  if (!(await courseBelongsToUser(parsed.data.courseId, userId))) {
    return { error: "Course not found" };
  }

  // Never trust the size the browser claimed when requesting the upload
  // URL — this is the real, storage-verified size of what actually landed.
  const head = await headObject(parsed.data.storageKey);
  if (!head) {
    return { error: "Upload not found in storage — please try again" };
  }
  if (head.sizeBytes > MAX_UPLOAD_BYTES) {
    await deleteObject(parsed.data.storageKey).catch(() => {});
    return { error: "File is larger than the 25MB limit" };
  }

  const material = await StudyMaterial.create({
    userId,
    courseId: parsed.data.courseId ? new Types.ObjectId(parsed.data.courseId) : null,
    originalFilename: parsed.data.originalFilename,
    format: keyInfo.format,
    fileSizeBytes: head.sizeBytes,
    storageKey: parsed.data.storageKey,
    status: "uploaded",
  });

  const materialId = material._id.toString();
  // Deliberately not awaited — see processing.ts's docstring for why that's
  // safe in this app's deployment shape.
  processStudyMaterial(materialId).catch((error: unknown) => {
    console.error(`Background processing crashed for material ${materialId}:`, error);
  });

  revalidatePath("/dashboard/materials");

  return { materialId };
}

export async function deleteMaterial(materialId: string): Promise<void> {
  const userId = await requireUserId();
  await connectToDatabase();

  const material = await StudyMaterial.findOneAndDelete({ _id: materialId, userId });
  if (!material) return;

  await MaterialChunk.deleteMany({ materialId: material._id });
  await deleteObject(material.storageKey).catch((error: unknown) => {
    console.error(`Failed to delete object ${material.storageKey} from storage:`, error);
  });

  revalidatePath("/dashboard/materials");
}
